### ISSUE TITLE
Any tips how to use it?

### ISSUE THREAD

**Issue by 0312birdzhang** [pfirmstone/tizen-java-bindings#1]
Thanks a lot ;)

**Comment by pfirmstone** [comment]
Still for the adventurous, the work isn't complete, enlightenment uses 
macro's to generate other language bindings, I was originally writing 
the bindings by hand, then was going to generate, but haven't had time.

The intent is to embed the jvm with a java program as a C application in 
Tizen.

Cheers,

Peter.

**Comment by 0312birdzhang** [comment]
What a pity. 😭
